version "3"

services:
    web:
        image: node.js
        build: .
        ports: :
            - "8000:8000"
        environment:
            - NODE_ENV=production
        volumes:
            - .:/app
        deploy:
            replies: 3
            update_config:
                parallelism: 2
                delay: 10s
            restart_policy:
            condition: on-failure          
                
